### ISSUE TITLE
Alt groups and flags page can be deleted?

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/docs-archive#10]
This page can probably be deleted. It's out of date and redundant.
 https://github.com/RetroAchievements/docs/wiki/Alt-Groups-and-Flags

The same info is present on the https://github.com/RetroAchievements/docs/wiki/Achievement-Logic-Features page.

The only reason I've not just deleted it is a concern with broken links.

**Comment by kdecks** [comment]
I deleted it. Hopefully it doesn't cause any issues.

**Comment by meleu** [comment]
You can safely delete it. It's not used in the official docs.
