### ISSUE TITLE
create a doc about "how to submit good tickets"

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/docs-archive#11]
inspiration: https://stackoverflow.com/help/how-to-ask

The RA user **ImpliedKappa** posted a detailed guide on the forum that could be adapted to a doc page: http://retroachievements.org/viewtopic.php?t=6688

**Comment by kdecks** [comment]
Currently best covered in the FAQ
https://github.com/RetroAchievements/docs/wiki/FAQ#what-details-should-i-add-to-a-broken-achievement-report

**Comment by meleu** [comment]
Yeah. The ImpliedKappa post is very detailed and :sophisticated:. But to be fair I don't see regular users following all those steps (unfortunately).

I'm going to close this and maybe we can add a link to his post in the FAQ later.
