### ISSUE TITLE
dark background

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/docs-archive#2]
The official website and the https://retroachievements.github.io/ front page has a dark background. Then it would be nice to have a similar look & feel in the docs.

AFAIK the MkDocs Material theme doesn't provide a way to change the background so easily. It must be done by tweaking CSS.

@luchaos looks like you're familiar with CSS stuff. If you have some free time could you help on this front?

In [this post](https://github.com/squidfunk/mkdocs-material/issues/338) there's a guy who seems that made it.

**EDIT**: I think he shared his `extra.css` file here: https://github.com/fmaida/mkdocs-material-dark-theme
I'll try it as soon as I get home. :)

**Comment by luchaos** [comment]
@meleu for the sake of consistency it would be nice to have similar appearances, agreed. i'd love to give it a treat!
(i forked this repo some hours ago - just in case y'know ;)

**Comment by meleu** [comment]
@luchaos oh... The pages generation should be done by the [`generate-docs.sh` script](https://github.com/RetroAchievements/docs/blob/master/generate-docs.sh).

Then, if you're unable to run the script (not on a Linux-like system) you have to perform some tasks manually. Such as fetching the `.md` files from the wiki, and manually add the `pages:` section in `mkdocs.yml`.

Let me know if you need any help to generate the pages for your tests. ;-)

**Comment by meleu** [comment]
@luchaos I used this `extra.css` to get a dark background: https://github.com/fmaida/mkdocs-material-dark-theme

And here is the results (it's online, by the way):
![screenshot](https://user-images.githubusercontent.com/8508804/32783121-d117d710-c931-11e7-8227-bfe7a34b4401.png)

As you said "for the sake of consistency it would be nice to have similar appearances". Then I think we could try to change those cyan letters to that bright orange like we have on the landing page.

I suck at CSS, but if you know how to change it directly on the file, here it is: https://github.com/RetroAchievements/docs/blob/master/css/extra.css

Thanks in advance for all your help with this web stuff! 😉

**Comment by meleu** [comment]
looks like the light theme is OK. Let's close this issue for now.

Thanks again for all your help @luchaos .
