### ISSUE TITLE
feature request: check broken links before deploying

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/docs-archive#21]
Possible solutions:
- linkchecker: https://pypi.org/project/LinkChecker/
- wget sourcery

For now I'm using https://www.deadlinkchecker.com/, but, as an online tool, it can only check after the pages are deployed. The goal is to check for broken links before deploying.

**Comment by kdecks** [comment]
This is useful. Can it be done automatically?

**Comment by meleu** [comment]
My intention is to implement it on the [`generate-docs.sh` script](https://github.com/RetroAchievements/docs/blob/master/generate-docs.sh). I tried linkchecker and it seems ok, but not sure about how it runs on Cygwin.

Maybe some `wget` tricks can do the job, I just need to take some time reading the docs.

**Comment by meleu** [comment]
done in cbc26e6071f9831347ba6fa5220a1eaaf5fb37fd
