### ISSUE TITLE
create a page to list staff members

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/docs-archive#22]
@kdecks IMO the #welcome channel on our discord is bloated, making many new users simply ignore it.

That message listing the staff members is a cool info, but seems to be of little relevance to those just entering the server. Then I suggest moving that to a page here. Another benefit: it has a more dynamic way to edit it as needed (no need to be done only by the Discord message's author).

**Comment by kdecks** [comment]
I like the state of the welcome channel, but I also don't mind what you're suggesting here.

**Comment by meleu** [comment]
how about this?: https://github.com/RetroAchievements/docs/wiki/About-Us

I had to use html for the table. Using markdown would be a big mess.
