### ISSUE TITLE
Complete list of all homebrew games

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/docs-archive#27]
And links to download them.

And any other legal freeware titles too.

**Comment by meleu** [comment]
please, add them here: https://github.com/RetroAchievements/docs/wiki/Free-Games

**Comment by kdecks** [comment]
I felt like we had a page like this. This issue will be closed once the list has been updated.

**Comment by televandalist** [comment]
[homebrews.txt](https://github.com/RetroAchievements/docs/files/2856050/homebrews.txt)

There's a list of all 393 games in the database marked with the `~Homebrew~` tag, sorted by console number and name. Games that actually have achievements are marked with *

At the very least, it's a reference for adding them to the Wiki page.

**Comment by meleu** [comment]
Add links to all games on that list?!

Keeping it up to date sounds like fighting a losing battle. :ssweat:

**Comment by televandalist** [comment]
Well, the ones with sets at least :yee:

**Comment by kdecks** [comment]
Only need the ones with sets.
