### ISSUE TITLE
Discussion pages for the wiki

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/docs-archive#29]
Most wiki's have a back side which is for discussion on certain changes. Any ideas how we could have something like that here?

Something clean and unobtrusive, but allows to discussion concepts for specific pages.

I have one idea, just now:
The idea is for any time someone wants to have discussion on a specific page, they create an issue, Title it: ``Discussion for page [page name]``. Label it as discussion, post their discussion points and then close the issue (to hide it), other points of discussion can be added there as they come up, and the issue can stay closed.

But anyway, this is meant to be an open ended question. Any thoughts?

**Comment by meleu** [comment]
Agreed.

I'll start one right now

**Comment by kdecks** [comment]
we'll see how it goes.

**Comment by meleu** [comment]
oh, I didn't notice the "close the issue (to hide it)".

IMO it's not necessary.
