### ISSUE TITLE
Talk page: Achievement Logic Features

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/docs-archive#30]
I've noticed that the [Achievement Logic Features](https://github.com/RetroAchievements/docs/wiki/Achievement-Logic-Features) started to become very bloated and kinda hard to find info quickly.

Then I started to split the topics into separate pages. Then you can quickly go to the `AddSource` page, for example.

The problem is: there are many other pages linking to each one of those techniques. It'll be necessary to check other docs and fix the links.

**Comment by kdecks** [comment]
I'd say splitting it into separate pages is the way to go, fixing links is growing pains.

**Comment by meleu** [comment]
I'm going to work on the fix for "how to become a developer"
