### ISSUE TITLE
Talk Page: SubSource

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/docs-archive#33]
Currently the explanation on the [SubSource Flag page](https://github.com/RetroAchievements/docs/wiki/SubSource-Flag) refers to the example in the AddSource page. For clarity sake, it would be useful to have a specific SubSource example instead.

**Comment by Tsearo** [comment]
It looks like there is now examples of using SubSource on the page but the values given in the first **Advanced** example for negative numbers are for 32-bit but the memory size is 8-bit so it should be changed to ff for this specific example (other two are fine)

Old - 
![sub-old](https://user-images.githubusercontent.com/4047771/71596191-9e150100-2b0c-11ea-9813-1eae36686960.png)

Should be - 
![sub](https://user-images.githubusercontent.com/4047771/71596195-a1a88800-2b0c-11ea-8893-24b89d8337f5.png)

**Comment by meleu** [comment]
thanks
