### ISSUE TITLE
Failed to download Game Data: Credentials Invalid

### ISSUE THREAD

**Issue by Applemunch** [RetroAchievements/docs-archive#37]
I just signed up on RA a few days ago (ApplemunchRA) and when I tried to play Super Smash Bros. or  Super Mario World, it fails to load achievements and says "Failed to download game data: Credentials Invalid (0)" and I didn't know what to do. It seems like other people have gotten this issue, but nobody seemed to answer.

**Comment by meleu** [comment]
By looking at your profile it seems that you solved it.

I guess it was a problem because you didn't confirmed your account via that link sent to your email.
