### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/docs-archive#4]
Maybe we could put a table of contents at the top. Is there an easy way to do this?

**Comment by meleu** [comment]
Yes, there is. And it is already being done. Take a look here:

https://retroachievements.github.io/docs/FAQ/

The ToC is on the right, if you're on desktop, and on menu, if you're on mobile.

**Comment by kdecks** [comment]
I see

**Comment by meleu** [comment]
Closing this issue, then.
